#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2026 Hadi Chokr <hadichokr@icloud.com>

import argparse
import logging
import os
import shutil
import subprocess
import urllib.request
import yaml

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

KDE_DEPS_YAML = "https://invent.kde.org/sysadmin/repo-metadata/-/raw/master/distro-dependencies/fedora.yaml"

# dnf5 drop-in directory (overrides /etc/dnf/dnf.conf, last one wins per key)
DNF_DROPIN = "/etc/dnf/libdnf5.conf.d/90-kde-selfbuilt.conf"

# Exported for the final image build (step 2), same mechanism as kde-runtime-deps.txt
EXCLUDES_EXPORT = "/work/kde-excluded-pkgs.txt"
EXCLUDES_CTX = "/ctx/kde-excluded-pkgs.txt"


def load_targets(path="/ctx/targets.txt"):
    if not os.path.exists(path):
        return []
    with open(path) as f:
        return [line.strip() for line in f if line.strip() and not line.startswith("#")]


def load_ignored_projects(path="/ctx/kde-builder.yaml"):
    """Projects listed in ignore-projects are deliberately not part of the image,
    so their distro packages must not be installed either (e.g. sddm, oxygen)."""
    if not os.path.exists(path):
        return []
    with open(path) as f:
        cfg = yaml.safe_load(f)
    return list((cfg.get("global") or {}).get("ignore-projects") or [])


def run_kde_builder(args):
    args = ["kde-builder"] + args
    logger.info(f"Running: {' '.join(args)}")
    process = subprocess.run(args=args, capture_output=True, text=True)
    if process.returncode != 0:
        raise Exception(f"kde-builder failed ({process.returncode}): {process.stdout}")
    return process.stdout


def get_all_build_targets(targets):
    logger.info("Querying kde-builder for true build targets...")
    result = subprocess.run(
        ["kde-builder", "--include-dependencies", "--no-stop-on-failure", "--pretend"] + targets,
        capture_output=True,
        text=True,
    )
    resolved = []
    for line in result.stdout.splitlines():
        if "Building " in line:
            part = line.split("Building ", 1)[1]
            module = part.split()[0].split("/")[-1]
            resolved.append(module)
    return resolved


def fetch_deps_yaml(url):
    logger.info(f"Fetching metadata from {url}")
    with urllib.request.urlopen(url) as f:
        return yaml.full_load(f)


def compute_excluded_packages(data, build_modules, ignored_modules):
    """Fedora package names that must never come from the distro:
    everything we build ourselves + everything on the ignore list."""
    excluded = set()
    for mod in set(build_modules) | set(ignored_modules):
        # best effort: the module name itself usually matches the package name
        excluded.add(mod)
        entry = data.get(mod) or {}
        excluded.update(entry.get("fedora_package") or [])
    return excluded


def collect_deps(data, build_modules):
    build_modules = set(build_modules)
    builddeps = set()
    rundeps = set()
    for name, pkg in data.items():
        if name not in build_modules:
            continue
        builddeps.update(pkg.get("builddeps") or [])
        rundeps.update(pkg.get("rundeps") or [])
    return builddeps, rundeps


def write_dnf_dropin(excluded):
    """Make every future dnf5 invocation (hotfix installs, group installs,
    layering in the final image) refuse to pull the excluded packages back in.

    NOTE: excludepkgs is replaced, not merged, and this drop-in overrides
    /etc/dnf/dnf.conf — so the *.i686 exclude from bootstrap must be repeated
    here or it would silently be re-enabled."""
    os.makedirs(os.path.dirname(DNF_DROPIN), exist_ok=True)
    value = ",".join(["*.i686"] + sorted(excluded))
    with open(DNF_DROPIN, "w") as f:
        f.write("# Generated by install-kde-deps.py — packages built from source\n")
        f.write("# or ignored via kde-builder ignore-projects. Do not install from repos.\n")
        f.write(f"[main]\nexcludepkgs={value}\n")
    logger.info(f"Wrote dnf exclude drop-in with {len(excluded)} packages to {DNF_DROPIN}")


def remove_installed(excluded):
    """Purge any excluded package that is already present (base image content,
    or dragged in transitively before the drop-in existed). Uses rpm --nodeps:
    dnf can no longer see these packages because of excludepkgs, and a dnf
    remove would also rip out legitimate dependents like flatpak. The library
    files are replaced by our own builds installing into /usr anyway."""
    installed = []
    for pkg in sorted(excluded):
        rc = subprocess.run(
            ["rpm", "-q", pkg],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        ).returncode
        if rc == 0:
            installed.append(pkg)
    if not installed:
        logger.info("No excluded packages present on the system, nothing to remove.")
        return
    logger.info(f"Removing {len(installed)} excluded package(s): {', '.join(installed)}")
    subprocess.run(["rpm", "-e", "--nodeps"] + installed, check=True)


def install(packages):
    packages = sorted(set(packages))
    if not packages:
        logger.info("No packages to install.")
        return
    logger.info(f"Installing {len(packages)} packages via dnf5: {', '.join(packages)}")
    process = subprocess.run(
        ["dnf5", "install", "-y", "--skip-broken", "--skip-unavailable", "--allowerasing"] + packages
    )
    if process.returncode != 0:
        raise Exception(f"dnf5 install failed ({process.returncode})")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--compile", action="store_true", help="Run in compilation mode to build targets and export runtime deps list")
    args = parser.parse_args()

    targets = load_targets()

    if args.compile:
        # Step 1: Run inside the transient compilation container (kde-build-container.sh)
        config_dir = "/root/.config"
        os.makedirs(config_dir, exist_ok=True)
        if os.path.exists("/ctx/kde-builder.yaml"):
            shutil.copy("/ctx/kde-builder.yaml", f"{config_dir}/kde-builder.yaml")

        run_kde_builder(["--metadata-only"])
        all_targets = get_all_build_targets(targets)
        ignored = load_ignored_projects()

        data = fetch_deps_yaml(KDE_DEPS_YAML)
        builddeps, rundeps = collect_deps(data, all_targets)
        excluded = compute_excluded_packages(data, all_targets, ignored)

        # 1. Never let dnf see the self-built/ignored packages again
        write_dnf_dropin(excluded)

        # 2. Install everything needed to compile, minus anything we provide ourselves
        to_install = (builddeps | rundeps) - excluded
        install(to_install)

        # 3. Purge anything from the exclude list that is still on the system
        #    (preinstalled in the base image or pulled in before the drop-in).
        #    This is what prevents a stale distro lib (e.g. libappstream) from
        #    shadowing the freshly built one at build time.
        remove_installed(excluded)

        # Export isolated runtime-only dependencies for the downstream final image
        runtime_final = rundeps - excluded
        os.makedirs(os.path.dirname(EXCLUDES_EXPORT), exist_ok=True)
        with open("/work/kde-runtime-deps.txt", "w") as f:
            f.write("\n".join(sorted(runtime_final)))
        logger.info("Exported runtime dependencies list to /work/kde-runtime-deps.txt")

        # Export the exclude list so the final image can apply the same policy
        with open(EXCLUDES_EXPORT, "w") as f:
            f.write("\n".join(sorted(excluded)))
        logger.info(f"Exported package exclude list to {EXCLUDES_EXPORT}")

    else:
        # Step 2: Run inside the final image (build.sh)
        # Apply the same excludes there: protects the extracted KDE tar from
        # ever being overwritten by distro packages (dnf layering, hotfixes).
        if os.path.exists(EXCLUDES_CTX):
            with open(EXCLUDES_CTX) as f:
                excluded = {line.strip() for line in f if line.strip()}
            write_dnf_dropin(excluded)
            remove_installed(excluded)
        else:
            excluded = set()
            logger.warning(f"No exclude list at {EXCLUDES_CTX}, skipping dnf drop-in.")

        deps_file = "/ctx/kde-runtime-deps.txt"
        if os.path.exists(deps_file):
            with open(deps_file) as f:
                runtime_deps = [line.strip() for line in f if line.strip() and line.strip() not in excluded]
            logger.info("Installing final image runtime requirements...")
            install(runtime_deps)
        else:
            logger.error(f"Required dependency tracking file missing at {deps_file}")


if __name__ == "__main__":
    main()
